language: java
jdk: oraclejdk11
services: docker

branches:
  except:
    - /^release-\d+\.\d+(\.\d+)?(-\S*)?$/

# install: ./gradlew assemble
# script: ./gradlew check
script: echo "OK"
# after_success: bash .travis/coverage.sh

# Try to release
deploy:
  skip_cleanup: true
  provider: script
  script: bash .travis/release.sh
  on:
    tags: false

# Cache some gradle folders
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Send notification to slack
notifications:
  slack: coditory:q1sUsgYeeAGZ7KSogB9GZvjZ
